name: 'Generate Allure Report with history'
description: 'Generate Allure Report with history'
author: 'simple-elf'
branding:
  icon: 'layout'
  color: 'green'
inputs:
  allure_results:
    description: 'Allure test result data dir'
    required: true
    default: 'allure-results'
  allure_report:
    description: 'Allure report target dir'
    required: true
    default: 'allure-report'
  gh_pages:
    description: 'Folder with gh-pages branch'
    required: true
    default: 'gh-pages'
  allure_history:
    description: 'Folder for allure history'
    required: true
    default: 'allure-history'
  subfolder:
    description: 'subfolder'
    required: false
    default: ''
  keep_reports:
    description: 'Keep X last reports'
    required: false
    default: '20'
  github_run_num:
    description: 'GitHub Actions build number'
    required: true
    default: ${{ github.run_number }}
  github_run_id:
    description: 'GitHub Actions run id'
    required: true
    default: ${{ github.run_id }}
  github_repo:
    description: 'GitHub repository'
    required: true
    default: ${{ github.repository }}
  github_repo_owner:
    description: 'GitHub repository owner'
    required: true
    default: ${{ github.repository_owner }}
  report_url:
    description: 'Use a custom URL instead of *.github.io'
    required: false
    default: ''
  github_server_url:
    description: 'GitHub server URL'
    required: true
    default: ${{ github.server_url }}
  allure_report_name:
    description: 'If you want custom Allure report name then you can mention here the default report name is Allure Report with history'
    required: false
    default: 'Allure Report with history'
  remote_repo_name:
    description: 'Remote repo name, this is required if you want to deploy results to a remote repository using Github Pages'
    required: false
    default: ${{ github.repository }}
runs:
  using: 'docker'
  image: 'Dockerfile'
